#server:
#  port: 8080
##  servlet:
##    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/purchase?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



# application.yml
## 通过指定type-aliases-package，MyBatis将会扫描该包路径下的所有类，并自动为它们注册别名，默认情况下，别名就是类的简单名称（首字母小写）\
mybatis:
  mapper-locations: classpath:/mapper/*.xml

